# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1270, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupLoad = QtWidgets.QGroupBox(self.centralwidget)
        self.groupLoad.setGeometry(QtCore.QRect(20, 30, 231, 311))
        self.groupLoad.setObjectName("groupLoad")
        self.loadFolder = QtWidgets.QPushButton(self.groupLoad)
        self.loadFolder.setGeometry(QtCore.QRect(10, 60, 211, 32))
        self.loadFolder.setObjectName("loadFolder")
        self.loadImageL = QtWidgets.QPushButton(self.groupLoad)
        self.loadImageL.setGeometry(QtCore.QRect(10, 140, 211, 32))
        self.loadImageL.setObjectName("loadImageL")
        self.loadImageR = QtWidgets.QPushButton(self.groupLoad)
        self.loadImageR.setGeometry(QtCore.QRect(10, 220, 211, 32))
        self.loadImageR.setObjectName("loadImageR")
        self.labelLoadFolder = QtWidgets.QLabel(self.groupLoad)
        self.labelLoadFolder.setGeometry(QtCore.QRect(20, 90, 191, 16))
        self.labelLoadFolder.setObjectName("labelLoadFolder")
        self.labelLoadImageL = QtWidgets.QLabel(self.groupLoad)
        self.labelLoadImageL.setGeometry(QtCore.QRect(20, 170, 191, 16))
        self.labelLoadImageL.setObjectName("labelLoadImageL")
        self.labelLoadImageR = QtWidgets.QLabel(self.groupLoad)
        self.labelLoadImageR.setGeometry(QtCore.QRect(20, 250, 191, 16))
        self.labelLoadImageR.setObjectName("labelLoadImageR")
        self.groupFindContour = QtWidgets.QGroupBox(self.centralwidget)
        self.groupFindContour.setGeometry(QtCore.QRect(270, 30, 231, 311))
        self.groupFindContour.setObjectName("groupFindContour")
        self.btn1_1 = QtWidgets.QPushButton(self.groupFindContour)
        self.btn1_1.setGeometry(QtCore.QRect(10, 90, 211, 32))
        self.btn1_1.setObjectName("btn1_1")
        self.btn1_2 = QtWidgets.QPushButton(self.groupFindContour)
        self.btn1_2.setGeometry(QtCore.QRect(10, 170, 211, 32))
        self.btn1_2.setObjectName("btn1_2")
        self.labelCountRings2 = QtWidgets.QLabel(self.groupFindContour)
        self.labelCountRings2.setGeometry(QtCore.QRect(20, 220, 191, 16))
        self.labelCountRings2.setObjectName("labelCountRings2")
        self.labelCountRings1 = QtWidgets.QLabel(self.groupFindContour)
        self.labelCountRings1.setGeometry(QtCore.QRect(20, 200, 191, 16))
        self.labelCountRings1.setObjectName("labelCountRings1")
        self.groupCalibration = QtWidgets.QGroupBox(self.centralwidget)
        self.groupCalibration.setGeometry(QtCore.QRect(520, 30, 231, 311))
        self.groupCalibration.setObjectName("groupCalibration")
        self.btn2_1 = QtWidgets.QPushButton(self.groupCalibration)
        self.btn2_1.setGeometry(QtCore.QRect(10, 30, 211, 32))
        self.btn2_1.setObjectName("btn2_1")
        self.btn2_2 = QtWidgets.QPushButton(self.groupCalibration)
        self.btn2_2.setGeometry(QtCore.QRect(10, 70, 211, 32))
        self.btn2_2.setObjectName("btn2_2")
        self.groupFindExtrinsic = QtWidgets.QGroupBox(self.groupCalibration)
        self.groupFindExtrinsic.setGeometry(QtCore.QRect(10, 110, 211, 101))
        self.groupFindExtrinsic.setObjectName("groupFindExtrinsic")
        self.btn2_3 = QtWidgets.QPushButton(self.groupFindExtrinsic)
        self.btn2_3.setGeometry(QtCore.QRect(0, 60, 211, 32))
        self.btn2_3.setObjectName("btn2_3")
        self.comboBoxFindExtrinsic = QtWidgets.QComboBox(
            self.groupFindExtrinsic)
        self.comboBoxFindExtrinsic.setGeometry(QtCore.QRect(20, 30, 171, 26))
        self.comboBoxFindExtrinsic.setObjectName("comboBoxFindExtrinsic")
        for i in range(1, 16):
            self.comboBoxFindExtrinsic.addItem(str(i))
        self.btn2_4 = QtWidgets.QPushButton(self.groupCalibration)
        self.btn2_4.setGeometry(QtCore.QRect(10, 220, 211, 32))
        self.btn2_4.setObjectName("btn2_4")
        self.btn2_5 = QtWidgets.QPushButton(self.groupCalibration)
        self.btn2_5.setGeometry(QtCore.QRect(10, 260, 211, 32))
        self.btn2_5.setObjectName("btn2_5")
        self.groupFindExtrinsic.raise_()
        self.btn2_1.raise_()
        self.btn2_2.raise_()
        self.btn2_4.raise_()
        self.btn2_5.raise_()
        self.groupAR = QtWidgets.QGroupBox(self.centralwidget)
        self.groupAR.setGeometry(QtCore.QRect(770, 30, 231, 311))
        self.groupAR.setObjectName("groupAR")
        self.btn3_1 = QtWidgets.QPushButton(self.groupAR)
        self.btn3_1.setGeometry(QtCore.QRect(10, 140, 211, 32))
        self.btn3_1.setObjectName("btn3_1")
        self.btn3_2 = QtWidgets.QPushButton(self.groupAR)
        self.btn3_2.setGeometry(QtCore.QRect(10, 220, 211, 32))
        self.btn3_2.setObjectName("btn3_2")
        self.lineEditAR = QtWidgets.QLineEdit(self.groupAR)
        self.lineEditAR.setGeometry(QtCore.QRect(20, 70, 191, 21))
        self.lineEditAR.setText("")
        self.lineEditAR.setObjectName("lineEditAR")
        self.groupStereoDisparityMap = QtWidgets.QGroupBox(self.centralwidget)
        self.groupStereoDisparityMap.setGeometry(
            QtCore.QRect(1020, 30, 231, 311))
        self.groupStereoDisparityMap.setObjectName("groupStereoDisparityMap")
        self.btn4_1 = QtWidgets.QPushButton(self.groupStereoDisparityMap)
        self.btn4_1.setGeometry(QtCore.QRect(10, 140, 211, 32))
        self.btn4_1.setObjectName("btn4_1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1270, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(
            _translate("MainWindow", "2022 OpenCvDl Hw2 "))
        self.groupLoad.setTitle(_translate("MainWindow", "Load Date"))
        self.loadFolder.setText(_translate("MainWindow", "Load Folder"))
        self.loadImageL.setText(_translate("MainWindow", "Load Image_L"))
        self.loadImageR.setText(_translate("MainWindow", "Load Image_R"))
        self.labelLoadFolder.setText(
            _translate("MainWindow", "No folder loaded"))
        self.labelLoadImageL.setText(
            _translate("MainWindow", "No image loaded"))
        self.labelLoadImageR.setText(
            _translate("MainWindow", "No image loaded"))
        self.groupFindContour.setTitle(
            _translate("MainWindow", "1. Find Contour"))
        self.btn1_1.setText(_translate("MainWindow", "1.1 Draw Contour"))
        self.btn1_2.setText(_translate("MainWindow", "1.2 Count Rings"))
        self.labelCountRings2.setText(
            _translate("MainWindow", "There are ___ rings in img2.jpg"))
        self.labelCountRings1.setText(
            _translate("MainWindow", "There are ___ rings in img1.jpg"))
        self.groupCalibration.setTitle(
            _translate("MainWindow", "2. Calibration"))
        self.btn2_1.setText(_translate("MainWindow", "2.1 Find Corners"))
        self.btn2_2.setText(_translate("MainWindow", "2.2 Find Intrinsic"))
        self.groupFindExtrinsic.setTitle(
            _translate("MainWindow", "2.3 Find Extrinsic"))
        self.btn2_3.setText(_translate("MainWindow", "2.3  Find Extrinsic"))
        self.btn2_4.setText(_translate("MainWindow", "2.4 Find Distortion"))
        self.btn2_5.setText(_translate("MainWindow", "2.5 Show Result"))
        self.groupAR.setTitle(_translate("MainWindow", "3. Augmented Reality"))
        self.btn3_1.setText(_translate("MainWindow",
                                       "3.1 Show Words on Board"))
        self.btn3_2.setText(
            _translate("MainWindow", "3.2 Show Words Vertically"))
        self.groupStereoDisparityMap.setTitle(
            _translate("MainWindow", "4. Stereo Disparity Map"))
        self.btn4_1.setText(
            _translate("MainWindow", "4.1 Stereo Disparity Map"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
